# Branch Protection Rules Configuration
# Note: This file documents the recommended branch protection settings
# The settings need to be applied manually in the GitHub web interface
# at: https://github.com/YOUR-USERNAME/yastwai/settings/branches

main:
  protection:
    required_status_checks:
      # Require branches to be up to date before merging
      strict: true
      
      # Status checks that are required
      contexts:
        - "Run tests"
        - "Clippy linting"
        - "Build on ubuntu-latest"
        - "Build on macos-latest"
        - "Build on windows-latest"
        - "Check PR title format"
        - "Check PR description"
    
    # Require at least one approval for PRs
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    
    # Do not allow bypassing the above settings
    enforce_admins: true
    
    # Allow only squash/rebase merging, no direct commits
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false 