name: PR Status Check

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  title-check:
    name: Check PR title format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true

  description-check:
    name: Check PR description
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR has description
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          if [[ -z "$PR_BODY" ]]; then
            echo "::error::PR description is empty. Please add a meaningful description."
            exit 1
          fi
          
          if [[ ${#PR_BODY} -lt 50 ]]; then
            echo "::warning::PR description is quite short. Consider adding more details."
          fi 